module.exports = {
  "app.js":  require('./app.js'),
  "crypto.js":  require('./crypto.js'),
  "file-input.js":  require('./file-input.js'),
  "message-confirm.js":  require('./message-confirm.js'),
  "sbot.js": require('./sbot.js'),
  "about.js":  require('./about.js'),
  "avatar-image.js":  require('./avatar-image.js'),
  "avatar-edit.js":  require('./avatar-edit.js'),
  "avatar-link.js":  require('./avatar-link.js'),
  "avatar-name.js":  require('./avatar-name.js'),
  "avatar-profile.js":  require('./avatar-profile.js'),
  "avatar.js":  require('./avatar.js'),
  "compose.js":  require('./compose.js'),
  "feed.js":  require('./feed.js'),
  "follow.js":  require('./follow.js'),
  "star.js":  require('./star.js'),
  "git.js":  require('./git.js'),
  "message.js":  require('./message.js'),
  "edit.js": require('./edit.js'),
  "names.js":  require('./names.js'),
  "post.js":  require('./post.js'),
  "private.js":  require('./private.js'),
  "public.js":  require('./public.js'),
  "relationships.js":  require('./relationships.js'),
  "suggest-mentions.js":  require('./suggest-mentions.js'),
  "thread.js":  require('./thread.js'),
  "suggest-emoji.js":  require('./suggest-emoji.js'),
  "key.js":  require('./key.js'),
  "notifications.js":  require('./notifications.js'),
  "search.js": require('./search')
}

